version: '3.8'

services:
  chatroom:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatroom:latest
    container_name: chatroom-prod
    ports:
      - "${PORT:-9090}:9090"
    environment:
      - PORT=9090
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.chatroom.description=Chat Room Pub-Sub System - Production"
      - "com.chatroom.version=1.0"
      - "com.chatroom.environment=production"
    networks:
      - chatroom-prod-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: chatroom-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - chatroom
    networks:
      - chatroom-prod-network
    restart: unless-stopped
    profiles:
      - with-proxy

networks:
  chatroom-prod-network:
    driver: bridge
    name: chatroom-prod-net

# Optional: Add volumes for persistent data if needed
volumes:
  chatroom-logs:
    driver: local
